language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - g++-6
    - cmake-data
    - cmake
install: cmake . && make
